/******************************************************************************/
/***               Generated by IBExpert 20.05.2010 14:00:00                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE SERVICES (
    SERVICE_ID  P_KEY /* P_KEY = INTEGER NOT NULL */,
    "TYPE"      S_10_NN /* S_10_NN = VARCHAR(10) NOT NULL */,
    NUM         INT_NN /* INT_NN = INTEGER NOT NULL */,
    NAME        S_70_NN /* S_70_NN = VARCHAR(70) NOT NULL */,
    VISIBLE     SMALLINT_NN DEFAULT 0 /* SMALLINT_NN = SMALLINT NOT NULL */,
    IS_EDIT     SMALLINT_NN DEFAULT 0 /* SMALLINT_NN = SMALLINT NOT NULL */
);




/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE SERVICES ADD CONSTRAINT PK_SERVICES PRIMARY KEY (SERVICE_ID);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE SERVICES ADD CONSTRAINT FK_SERVICES_SERV_TYPES FOREIGN KEY ("TYPE") REFERENCES SERV_TYPES ("TYPE");


/******************************************************************************/
/***                          Fields descriptions                           ***/
/******************************************************************************/

COMMENT ON COLUMN SERVICES.SERVICE_ID IS 
'ID услуги';

COMMENT ON COLUMN SERVICES."TYPE" IS 
'Вид услуги';

COMMENT ON COLUMN SERVICES.NUM IS 
'Номер услуги (уникальный)';

COMMENT ON COLUMN SERVICES.NAME IS 
'Наименование услуги';

COMMENT ON COLUMN SERVICES.VISIBLE IS 
'Отображение услуги';

COMMENT ON COLUMN SERVICES.IS_EDIT IS 
'Признак возможности редактировать поле
0 - нельзя редактировать
1 - можно редактировать';