/******************************************************************************/
/***               Generated by IBExpert 20.05.2010 14:00:00                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE SUBSRV (
    SUBSRV_ID   P_KEY /* P_KEY = INTEGER NOT NULL */,
    SERVICE_ID  F_KEY NOT NULL /* F_KEY = INTEGER */,
    SUB_SRV_PU  S_70_NN /* S_70_NN = VARCHAR(70) NOT NULL */,
    NAME        S_70_NN /* S_70_NN = VARCHAR(70) NOT NULL */
);




/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE SUBSRV ADD CONSTRAINT PK_SUBSRV PRIMARY KEY (SUBSRV_ID);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE SUBSRV ADD CONSTRAINT FK_SUBSRV_SERVICES FOREIGN KEY (SERVICE_ID) REFERENCES SERVICES (SERVICE_ID);


/******************************************************************************/
/***                          Fields descriptions                           ***/
/******************************************************************************/

COMMENT ON COLUMN SUBSRV.SUBSRV_ID IS 
'ID подуслуги';

COMMENT ON COLUMN SUBSRV.SERVICE_ID IS 
'Ссылка на ИД услуги';

COMMENT ON COLUMN SUBSRV.SUB_SRV_PU IS 
'ID подуслуги в системе ПУ';

COMMENT ON COLUMN SUBSRV.NAME IS 
'Наименование подуслуги';