/******************************************************************************/
/***               Generated by IBExpert 20.05.2010 14:00:00                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE STREET_LIST (
    STREET_ID  P_KEY /* P_KEY = INTEGER NOT NULL */,
    CITY_ID    F_KEY NOT NULL /* F_KEY = INTEGER */,
    NAME       S_70_NN /* S_70_NN = VARCHAR(70) NOT NULL */,
    IS_EDIT    SMALLINT_NN DEFAULT 0 /* SMALLINT_NN = SMALLINT NOT NULL */
);




/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE STREET_LIST ADD CONSTRAINT PK_STREET_LIST PRIMARY KEY (STREET_ID);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE STREET_LIST ADD CONSTRAINT FK_STREET_LIST_CITY FOREIGN KEY (CITY_ID) REFERENCES CITY_LIST (CITY_ID);


/******************************************************************************/
/***                          Fields descriptions                           ***/
/******************************************************************************/

COMMENT ON COLUMN STREET_LIST.STREET_ID IS 
'ID записи улицы';

COMMENT ON COLUMN STREET_LIST.CITY_ID IS 
'ID записи города';

COMMENT ON COLUMN STREET_LIST.NAME IS 
'Наименование улицы';

COMMENT ON COLUMN STREET_LIST.IS_EDIT IS 
'Признак возможности редактировать поле
0 - нельзя редактировать
1 - можно редактировать';