/******************************************************************************/
/***               Generated by IBExpert 20.05.2010 14:00:00                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE SALDO (
    SALDO_ID      P_KEY /* P_KEY = INTEGER NOT NULL */,
    ABONENT_ID    F_KEY NOT NULL /* F_KEY = INTEGER */,
    PERIOD_BEGIN  DATE_NN /* DATE_NN = DATE NOT NULL */,
    PERIOD_END    DATE_NN /* DATE_NN = DATE NOT NULL */,
    SUMM          FLOAT_10_2_NN /* FLOAT_10_2_NN = NUMERIC(10,2) NOT NULL */,
    IS_EXPORT     SMALLINT_NN DEFAULT 0 /* SMALLINT_NN = SMALLINT NOT NULL */
);




/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE SALDO ADD CONSTRAINT PK_SALDO PRIMARY KEY (SALDO_ID);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE SALDO ADD CONSTRAINT FK_SALDO_ABONENT FOREIGN KEY (ABONENT_ID) REFERENCES ABONENTS (ABONENT_ID);


/******************************************************************************/
/***                          Fields descriptions                           ***/
/******************************************************************************/

COMMENT ON COLUMN SALDO.SALDO_ID IS 
'ИД задолженности';

COMMENT ON COLUMN SALDO.ABONENT_ID IS 
'Ссылка на ИД абонента';

COMMENT ON COLUMN SALDO.PERIOD_BEGIN IS 
'Начальный период начислений';

COMMENT ON COLUMN SALDO.PERIOD_END IS 
'Конечный период начислений';

COMMENT ON COLUMN SALDO.SUMM IS 
'Сумма';

COMMENT ON COLUMN SALDO.IS_EXPORT IS 
'Признак выгрузки начислений
0 - не выгружены
1 - выгружены';