CREATE TABLE DSM.OPER_TYPES
(
  ID    NUMBER                                  NOT NULL,
  NAME  VARCHAR2(50 BYTE)                       NOT NULL,
  CODE  VARCHAR2(50 BYTE),
  SIGN  INTEGER                                 NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE DSM.OPER_TYPES IS 'Типы операций';

COMMENT ON COLUMN DSM.OPER_TYPES.ID IS 'ID операции';

COMMENT ON COLUMN DSM.OPER_TYPES.NAME IS 'Описание';

COMMENT ON COLUMN DSM.OPER_TYPES.CODE IS 'Код';

COMMENT ON COLUMN DSM.OPER_TYPES.SIGN IS 'Знак (-1 - отгрузка или продажа, 1 - приход)';


CREATE UNIQUE INDEX DSM.OPER_TYPES_PK ON DSM.OPER_TYPES
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE DSM.OPER_TYPES ADD (
  CONSTRAINT OPER_TYPES_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

