CREATE TABLE DSM.OPERATIONS
(
  ID             NUMBER                         NOT NULL,
  OPER_TYPE_ID   NUMBER                         NOT NULL,
  DOC_DATE       DATE                           NOT NULL,
  EMPLOYEE_ID    NUMBER                         NOT NULL,
  PRODUCT_ID     NUMBER                         NOT NULL,
  AMOUNT         INTEGER                        NOT NULL,
  PRICE_FOR_ONE  NUMBER(15,2),
  CLIENT_ID      NUMBER                         
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE DSM.OPERATIONS IS 'Операции на складе';

COMMENT ON COLUMN DSM.OPERATIONS.ID IS 'ID операции';

COMMENT ON COLUMN DSM.OPERATIONS.OPER_TYPE_ID IS 'Тип операции';

COMMENT ON COLUMN DSM.OPERATIONS.DOC_DATE IS 'Дата операции';

COMMENT ON COLUMN DSM.OPERATIONS.EMPLOYEE_ID IS 'ID кладовщика';

COMMENT ON COLUMN DSM.OPERATIONS.PRODUCT_ID IS 'ID товара';

COMMENT ON COLUMN DSM.OPERATIONS.AMOUNT IS 'Количество товара';

COMMENT ON COLUMN DSM.OPERATIONS.PRICE_FOR_ONE IS 'Цена за единицу товара';

COMMENT ON COLUMN DSM.OPERATIONS.CLIENT_ID IS 'ID клиента';


CREATE UNIQUE INDEX DSM.OPERATIONS_PK ON DSM.OPERATIONS
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE DSM.OPERATIONS ADD (
  CONSTRAINT OPERATIONS_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE DSM.OPERATIONS ADD (
  CONSTRAINT FK_OPER_PRODUCT_ID 
 FOREIGN KEY (PRODUCT_ID) 
 REFERENCES DSM.PRODUCTS,
  CONSTRAINT FK_CLIENT_ID 
 FOREIGN KEY (CLIENT_ID) 
 REFERENCES DSM.CLIENTS,
  CONSTRAINT FK_EMPLOYEE_ID 
 FOREIGN KEY (EMPLOYEE_ID) 
 REFERENCES DSM.EMPLOYEES,
  CONSTRAINT FK_OPER_TYPE_ID 
 FOREIGN KEY (OPER_TYPE_ID) 
 REFERENCES DSM.OPER_TYPES);

