object Form1: TForm1
  Left = 208
  Top = 200
  Width = 405
  Height = 196
  Caption = #1041#1072#1085#1077#1088
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
  object Timer1: TTimer
    Left = 8
    Top = 136
  end
end
