
/******************************************************************************/
/***               Generated by IBExpert 20.05.2010 14:00:00                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE ABONENTS (
    ABONENT_ID    P_KEY /* P_KEY = INTEGER NOT NULL */,
    SERVICE_ID    F_KEY NOT NULL /* F_KEY = INTEGER */,
    SUBSRV_ID     F_KEY DEFAULT NULL /* F_KEY = INTEGER */,
    CITY_ID       F_KEY DEFAULT NULL /* F_KEY = INTEGER */,
    STREET_ID     F_KEY NOT NULL /* F_KEY = INTEGER */,
    FIO           S_70 DEFAULT NULL /* S_70 = VARCHAR(70) */,
    BUILDING      S_10 DEFAULT NULL /* S_10 = VARCHAR(10) */,
    APARTMENT     S_7 DEFAULT NULL /* S_7 = VARCHAR(7) */,
    ACC_PU        S_40_NN NOT NULL /* S_40_NN = VARCHAR(40) NOT NULL */,
    OPEN_TIME     DATETIME_NN /* DATETIME_NN = TIMESTAMP NOT NULL */,
    CLOSE_TIME    DATETIME DEFAULT NULL /* DATETIME = TIMESTAMP */,
    IS_ACC_LOCK   SMALLINT_NN DEFAULT 0 /* SMALLINT_NN = SMALLINT NOT NULL */,
    IS_ACC_CLOSE  SMALLINT_NN DEFAULT 0 /* SMALLINT_NN = SMALLINT NOT NULL */,
    BALANCE       FLOAT_10_2_NN DEFAULT 0 /* FLOAT_10_2_NN = NUMERIC(10,2) NOT NULL */
);




/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE ABONENTS ADD CONSTRAINT PK_ABONENTS PRIMARY KEY (ABONENT_ID);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE ABONENTS ADD CONSTRAINT FK_ABONENTS_CITY FOREIGN KEY (CITY_ID) REFERENCES CITY_LIST (CITY_ID);
ALTER TABLE ABONENTS ADD CONSTRAINT FK_ABONENTS_SERVICE FOREIGN KEY (SERVICE_ID) REFERENCES SERVICES (SERVICE_ID);
ALTER TABLE ABONENTS ADD CONSTRAINT FK_ABONENTS_STREET FOREIGN KEY (STREET_ID) REFERENCES STREET_LIST (STREET_ID);
ALTER TABLE ABONENTS ADD CONSTRAINT FK_ABONENTS_SUBSRV FOREIGN KEY (SUBSRV_ID) REFERENCES SUBSRV (SUBSRV_ID);


/******************************************************************************/
/***                          Fields descriptions                           ***/
/******************************************************************************/

COMMENT ON COLUMN ABONENTS.ABONENT_ID IS 
'ИД абонента';

COMMENT ON COLUMN ABONENTS.SERVICE_ID IS 
'Ссылка на ИД услуги';

COMMENT ON COLUMN ABONENTS.SUBSRV_ID IS 
'Ссылка на ИД подуслуги';

COMMENT ON COLUMN ABONENTS.CITY_ID IS 
'Ссылка на ИД города';

COMMENT ON COLUMN ABONENTS.STREET_ID IS 
'Ссылка на ИД улицы';

COMMENT ON COLUMN ABONENTS.FIO IS 
'Фамилия, имя, отчество абонента';

COMMENT ON COLUMN ABONENTS.BUILDING IS 
'Номер дома из адреса абонента';

COMMENT ON COLUMN ABONENTS.APARTMENT IS 
'Номер квартиры из адреса абонента';

COMMENT ON COLUMN ABONENTS.ACC_PU IS 
'Лицевой счет';

COMMENT ON COLUMN ABONENTS.OPEN_TIME IS 
'Дата создания л/с абонента';

COMMENT ON COLUMN ABONENTS.CLOSE_TIME IS 
'Дата закрытия л/с абонента';

COMMENT ON COLUMN ABONENTS.IS_ACC_LOCK IS 
'Признак пометки лицевого счета на закрытие
0 - не помечен
1 - помечен';

COMMENT ON COLUMN ABONENTS.IS_ACC_CLOSE IS 
'Признак закрытия лицевого счета
0 - не закрыт
1 - закрыт';

COMMENT ON COLUMN ABONENTS.BALANCE IS 
'Текущая задолженность';



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/

