--DROP VIEW KP.V$UNATTACHED_STREETS_PU;

CREATE OR REPLACE VIEW KP.V$UNATTACHED_STREETS_PU
(ID, STREET_ID, STATUS)
AS 
SELECT ID
     , STREET_ID
     , STATUS
FROM KP.STREET_PU
WHERE STREET_ID IS NULL
AND STATUS = 'NEW';

GRANT SELECT, UPDATE ON KP.V$UNATTACHED_STREETS_PU TO DSM;