SELECT REC.ACC_PU
     , REC.SUB_SRV_PU
     , NVL(REC.DATEB, TRUNC(REC.DONE)) PERIOD_BEGIN
     , NVL(REC.DATEE, TRUNC(REC.DONE)) PERIOD_END
     , REC.SUMM
FROM KP.REE$REEARC ree 
   , KP.REE$RECINPARC rec
   , KP.AGRS agr
   , KP.SERVICES se 
WHERE REE.TYPE = 7
AND REE.ID = REC.REEID
AND REE.AGRID = AGR.ID
AND AGR.SERVICE_ID = SE.ID
AND REC.STATUS = 14
AND SE.NUM = 2981
ORDER BY REC.ACC_PU
       , REC.SUB_SRV_PU
       , REC.DONE