/* платежи по основной услуге */
SELECT REE.ID AS REE_ID
     , REE.AGENTID AS AGENT_ID
     , AB.SERVICE_ID
     , REC.SUB_SRV_PU
     , AB.FIO
     , CI.NAME AS CITY
     , ST.NAME AS STREET
     , AB.BUILDING
     , AB.APARTMENT
     , AB.ACC_PU
     , REC.SUMM
     , TRUNC(REE.CREATED) AS DATE_PAY
     , REC.BALANCE AS BALANCE
     , REC.UNO
FROM KP.REE$REESTERS ree
   , KP.REE$RECORDS rec
   , KP.ABONENTS ab
   , KP.AGRS ag
   , KP.SERVICES se
   , KP.CITY_LIST ci
   , KP.STREET_LIST st
WHERE REE.TYPE IN (2,4)
AND REE.ID        = REC.REEID
AND REC.ABNID     = AB.ID
AND AB.CITY_ID    = CI.ID
AND AB.STREET_ID  = ST.ID
AND REE.AGRID     = AG.ID
AND AG.SERVICE_ID = SE.ID
AND SE.NUM = 2645