/* платежи по дополнительной услуге */
SELECT REE.ID AS REE_ID
     , REE.AGENTID AS AGENT_ID
     , SE.ID AS SERVICE_ID
     , REC.FIO
     , REC.ADDRESS
     , REC.SUMM
     , TRUNC(REE.CREATED) AS DATE_PAY
     , REC.BALANCE AS BALANCE
     , REC.UNO
FROM KP.REE$REESTERS ree
   , KP.REE$RECORDS rec 
   , KP.AGRS ag
   , KP.SERVICES se
WHERE REE.TYPE IN (2,4)
AND REE.ID        = REC.REEID
AND REE.AGRID     = AG.ID
AND AG.SERVICE_ID = SE.ID
AND SE.NUM        = 2490
ORDER BY DATE_PAY